### PR TITLE
check that a target directory exists before committing to cd

### LINKED ISSUE #852: `spack cd` changes directory when no target exists
When the requested stage doesn't exist, `spack cd` changes directory to the user's home.  At least personally I would expect it to stay in the same directory in this case.

```
scogland at cab668 in /tmp/scogland/spack-stage/spack-stage-D1e76p
$ cd ~/spack

scogland at cab668 in ~/spack (e53571d...)
$ spack cd gcc
==> Error: Build directory does not exist yet. Run this to create it:
  spack stage gcc

scogland at cab668 in ~ (gem:32)
$ pwd
/g/g12/scogland
```

### PR DESCRIPTION
**Pull request by trws**
Fixes #852

### CODE REVIEW

File: share/spack/setup-env.sh [hunk 1]
```diff
@@ -84,7 +84,10 @@ function spack {
             if [ "$_sp_arg" = "-h" ]; then
                 command spack cd -h
             else
-                cd $(spack location $_sp_arg "$@")
+		LOC="$(spack location $_sp_arg "$@")"
+		if [[ "x" -ne "x$LOC" ]] ; then
```
Comment (adamjstewart) [inline share/spack/setup-env.sh]:
```bash
if [[ $LOC ]]; then
```
or even
```bash
if [[ -d $LOC ]]; then
```
would be preferable. See `man test`

Comment (trws) [inline share/spack/setup-env.sh]: Agreed on "-d", I'll put in an updated patch for that.


________________________________
