### PR TITLE
Use kcov from official Ubuntu 20.04 repository

### LINKED ISSUE #23164: Coverage failing with kcov 38
For historical reasons we are building kcov at version 3.4 from sources in our CI. The main motivation was that there was no system package for it in `ubuntu:18.04`, which was the default `ubuntu-latest` virtual environment for GitHub Actions up to not so long ago.

Since a while `ubuntu-latest` points to `ubuntu:20.04` and there is a `kcov-38` package installable using `apt`. That though gives linking failures during tests that might need to be investigated.

### Steps to reproduce the issue

See https://github.com/spack/spack/runs/2398568838?check_suite_focus=true 

### Error Message

Error message is in the logs above

### Information on your system

This happens on the `ubuntu-latest` virtual environment. So far I didn't try to reproduce it outside of it.

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by alalazo**
fixes https://github.com/spack/spack/issues/23164

Modifications:
- [x] Use kcov from Ubuntu 20.04 repository for shell tests
- [x] Use kcov from Ubuntu 20.04 repository for unit tests
- [x] Fix using kcov v3.8 with unit tests

### CODE REVIEW

**Comment by adamjstewart** [comment]
I feel like I looked into this once and the kcov that came with apt was far too old to use. Has a newer version been added?

**Comment by alalazo** [comment]
@adamjstewart No, the issue is the opposite: Ubuntu 18.04 (old default for Github Actions runner) didn't have a `kcov` package as far as I remember. The latest official version is the one in Ubuntu 20.04, but it never worked with our unit tests, so we were building an earlier one. I'll try to check why kcov v3.8 fails with our unit tests setup and hopefully push a fix here.

**Comment by alalazo** [comment]
For the record, I have been able to fix using the latest `kcov` (or at least I think so), but  I still have locally ~30 tests failing since coverage of bash script is based on PS4 and those tests check the output of the script. To be clear, under coverage we have something like:
```console
[ ... ]
+ rpaths+=("${implicit_rpaths[@]}")
+ args=()
+ args+=("${flags[@]}")
+ IFS=:
+ read -ra spack_include_dirs
+ [[ ccld == cpp ]]
+ [[ ccld == cc ]]
+ [[ ccld == as ]]
+ [[ ccld == ccld ]]
+ [[ '' == \t\r\u\e ]]
+ case "$mode" in
+ '[' -n --disable-new-dtags ']'
+ args+=("$linker_arg$dtags_to_add")
+ args+=("${other_args[@]}")
+ full_command=("$command" "${args[@]}")
+ '[' -n '' ']'
+ [[ dump-args == dump-args ]]
+ IFS='
'
+ echo '/bin/mycc
-Wl,--disable-new-dtags
-shared
-Wl,-soname,libfoo.so
-Wl,--whole-archive
/spack/libfoo.a
-Wl,--no-whole-archive
-o
/spack/libfoo.so'
+ exit
[ ... ]
```
instead of the expected:
```console
-Wl,--disable-new-dtags
-shared
-Wl,-soname,libfoo.so
-Wl,--whole-archive
/spack/libfoo.a
-Wl,--no-whole-archive
-o
/spack/libfoo.so
```

**Comment by adamjstewart** [comment]
Could we just unset PS4 when running that script?

**Comment by alalazo** [comment]
I think we can't since it's, as far as I understand, the preferred way to collect coverage lines. I didn't follow this rabbit hole into reading kcov34 source code (all later versions seem to fail) and checking why that version is working for us.

**Comment by adamjstewart** [comment]
Can we set PS4 to whatever is expected? My bashrc also overrides PS4 to something different.

**Comment by alalazo** [comment]
The latest changes seem to fix, with hidden config options, the unit tests - but shell tests are hanging :laughing:

**Comment by alalazo** [comment]
@tgamblin @becker33 This PR modifies our CI workflow to use kcov v38 (the one that comes with Ubuntu 20.04, default for Github Actions) so that we don't have to build an older version from sources. Overall kcov seems very sensitive to changes in e.g. the version of bash or of the operating system. 

There are two issues open under the kcov  repository (https://github.com/SimonKagstrom/kcov/issues/361 and https://github.com/SimonKagstrom/kcov/issues/362) that I'll try to follow on to see why certain things seem to be needed here to use versions later than v34.

**Review by becker33 — DISMISSED** [review]

File: share/spack/qa/setup.sh [hunk 1]
```diff
@@ -31,10 +31,10 @@ if [[ "$COVERAGE" == "true" ]]; then
     bashcov=$(realpath ${QA_DIR}/bashcov)
 
     # instrument scripts requiring shell coverage
-    sed -i~ "s@#\!/bin/bash@#\!${bashcov}@" "$SPACK_ROOT/lib/spack/env/cc"
+    sed -i "s@#\!/bin/bash@#\!${bashcov}@" "$SPACK_ROOT/lib/spack/env/cc"
     if [ "$(uname -o)" != "Darwin" ]; then
         # On darwin, #! interpreters must be binaries, so no sbang for bashcov
-        sed -i~ "s@#\!/bin/sh@#\!${bashcov}@"   "$SPACK_ROOT/bin/sbang"
```
Comment (adamjstewart) [inline share/spack/qa/setup.sh:37]: Doesn't BSD sed require an argument for the inplace flag?

Comment (becker33) [reply share/spack/qa/setup.sh:37]: MacOS certainly does

Comment (adamjstewart) [reply share/spack/qa/setup.sh:37]: macOS sed == BSD sed

Comment (alalazo) [reply share/spack/qa/setup.sh:37]: It's not strictly needed, as far as I understand (emphasis mine):

> Edit files in-place, saving backups with the specified extension.  **If a zero-length extension is given, no backup will be saved.**  It is not recommended to give a zero-length extension when in-place editing files, as you risk corruption or partial content in situations where disk space is exhausted, etc.


Also, on MacOS we don't use this script to run tests:

https://github.com/spack/spack/blob/cd91abcf880e61c63c10b0f51be67f482b2149fc/.github/workflows/unit_tests.yaml#L381-L397

as there are also other parts that are not compatible (if I recall correctly we use `realpath` somewhere which is not on Darwin). On Linux having this substitution results in having `~` file accounted for in coverage reports, at least with kcov38.

Comment (adamjstewart) [reply share/spack/qa/setup.sh:37]: I'm pretty sure it's needed on macOS (maybe `-i ''` is what they mean by zero-length extension) but as long as we don't run this test on macOS then it doesn't really matter.

Comment (alalazo) [reply share/spack/qa/setup.sh:37]: @adamjstewart @becker33 Ready for another review then :grimacing:

Comment (adamjstewart) [reply share/spack/qa/setup.sh:37]: Based on https://stackoverflow.com/questions/7573368/in-place-edits-with-sed-on-os-x I would use `-i ''` just in case. This shouldn't change anything on Linux and will allow things to work properly on Darwin. `setup.sh` is called by all of our unit testing scripts, so I assume we use it somewhere on macOS.

Comment (alalazo) [reply share/spack/qa/setup.sh:37]: I'll do the change, but I don't think this is true:

> setup.sh is called by all of our unit testing scripts, so I assume we use it somewhere on macOS.

The only place where we run tests on a MacOS runner is in the snippet above and:
```
% share/spack/qa/setup.sh 
share/spack/qa/setup.sh: line 14: realpath: command not found
share/spack/qa/setup.sh: line 17: /share/spack/setup-env.sh: No such file or directory
```

Comment (adamjstewart) [reply share/spack/qa/setup.sh:37]: We should probably not use realpath lol. I wrote an entire gist for this cuz I could never remember the best way to find an absolute path: https://gist.github.com/adamjstewart/c7629ed2ad89ed25513a82d3cb5d774e. But this can be fixed another day. As long as we aren't introducing additional Linux-isms.

**Review by adamjstewart — DISMISSED** [review]

File: share/spack/qa/setup.sh (hunk 1 above)
Comment (alalazo) [reply share/spack/qa/setup.sh:37]: @adamjstewart Reverted since using a zero-length argument with a space seems to cause failures on linux :slightly_frowning_face:

Comment (adamjstewart) [reply share/spack/qa/setup.sh:37]: Bleh, according to https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux it's just not possible to support both. Let's go with what you have now. If we ever need macOS support we can add an if-statement.

Comment (alalazo) [reply share/spack/qa/setup.sh:37]:
```
-i[SUFFIX], --in-place[=SUFFIX]

      edit files in place (makes backup if SUFFIX supplied)
```

**Review by adamjstewart — APPROVED** [review]

**Review by becker33 — APPROVED** [review]
